// Generated by CoffeeScript 1.7.1
(function() {
  var CanvasGraph, canvas, canvasState, zoomBtn;

  CanvasGraph = (function() {
    function CanvasGraph(canvas, data) {
      var point;
      this.canvas = canvas;
      this.data = data;
      this.ctx = this.canvas.getContext('2d');
      window.ctx = this.ctx;
      window.canvas = this.canvas;
      this.smallestX = Math.min.apply(Math, (function() {
        var _i, _len, _ref, _results;
        _ref = this.data;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          point = _ref[_i];
          _results.push(point.x);
        }
        return _results;
      }).call(this));
      this.smallestY = Math.min.apply(Math, (function() {
        var _i, _len, _ref, _results;
        _ref = this.data;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          point = _ref[_i];
          _results.push(point.y);
        }
        return _results;
      }).call(this));
      this.largestX = Math.max.apply(Math, (function() {
        var _i, _len, _ref, _results;
        _ref = this.data;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          point = _ref[_i];
          _results.push(point.x);
        }
        return _results;
      }).call(this));
      this.largestY = Math.max.apply(Math, (function() {
        var _i, _len, _ref, _results;
        _ref = this.data;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          point = _ref[_i];
          _results.push(point.y);
        }
        return _results;
      }).call(this));
      console.log(this.largestX);
    }

    CanvasGraph.prototype.drawAxes = function() {
      var num, _i, _j, _ref, _ref1;
      for (num = _i = 0, _ref = this.canvas.width; _i <= _ref; num = _i += 100) {
        this.ctx.moveTo(num - .5, 0);
        this.ctx.lineTo(num - .5, this.canvas.height);
      }
      for (num = _j = 0, _ref1 = this.canvas.height; _j <= _ref1; num = _j += 100) {
        this.ctx.moveTo(0, num - .5);
        this.ctx.lineTo(this.canvas.width, num - .5);
      }
      this.ctx.strokeStyle = "gray";
      return this.ctx.stroke();
    };

    CanvasGraph.prototype.plotPoints = function() {
      var point, x, y, _i, _len, _ref, _results;
      _ref = this.data;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        point = _ref[_i];
        x = ((point.x - this.smallestX) / (this.largestX - this.smallestX)) * this.canvas.width;
        y = ((point.y - this.largestY) / (this.smallestY - this.largestY)) * this.canvas.height;
        this.ctx.fillStyle = "#fff";
        _results.push(this.ctx.fillRect(x, y, 2, 2));
      }
      return _results;
    };

    CanvasGraph.prototype.plotZoomedPoints = function(xMin, xMax) {
      var point, x, y, _i, _len, _ref, _results;
      this.clearCanvas();
      _ref = this.data;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        point = _ref[_i];
        x = ((point.x - xMin) / (xMax - xMin)) * this.canvas.width;
        y = ((point.y - this.largestY) / (this.smallestY - this.largestY)) * this.canvas.height;
        this.ctx.fillStyle = "#fff";
        _results.push(this.ctx.fillRect(x, y, 2, 2));
      }
      return _results;
    };

    CanvasGraph.prototype.rescale = function() {
      this.clearCanvas();
      return this.plotPoints();
    };

    CanvasGraph.prototype.clearCanvas = function() {
      return this.ctx.clearRect(0, 0, this.canvas.width, this.canvas.height);
    };

    CanvasGraph.prototype.mirrorVertically = function() {
      this.ctx.translate(0, this.canvas.height);
      return this.ctx.scale(1, -1);
    };

    return CanvasGraph;

  })();

  canvas = document.getElementById("graph");

  canvasState = new CanvasGraph(canvas, light_curve_data);

  canvasState.plotPoints();

  canvas.addEventListener('mousedown', function(e) {
    console.log(e);
    return console.log(e.x - this.getBoundingClientRect().left, e.y - this.getBoundingClientRect().top);
  });

  canvas.addEventListener('mouseup', function(e) {
    console.log(e);
    return console.log(e.x - this.getBoundingClientRect().left, e.y - this.getBoundingClientRect().top);
  });

  zoomBtn = document.getElementById('toggle-zoom');

  zoomBtn.addEventListener('click', (function(_this) {
    return function(e) {
      _this.zoomed = !_this.zoomed;
      if (_this.zoomed) {
        return canvasState.plotZoomedPoints(5, 20);
      } else {
        return canvasState.rescale();
      }
    };
  })(this));

}).call(this);
